# Generated by Django 4.2.11 on 2024-04-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
