# Generated by Django 4.2.11 on 2024-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
    ]
