# Generated by Django 4.2.11 on 2024-04-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movies_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
    ]
