# Generated by Django 4.2.11 on 2024-04-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movies_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='created_by',
        ),
    ]
