# Generated by Django 4.2.11 on 2024-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_name',
            field=models.CharField(default=True, max_length=225),
        ),
    ]
